### PR TITLE
Added section on getting started and testing the bot

### LINKED ISSUE #16: Need "how to run" section
The readme does a great job demonstrating how to build everything up, but it's difficult to understand what steps are needed to just run the sample, which ends up leading to a lot of guesswork. 

Consider having a "Running this Sample" section at the top, with the fewest steps necessary, and then expanding on how it was built

### PR DESCRIPTION
**Pull request by KatieProchilo**
Closes #16 

Updated the README for the basic Node bot, including sections on getting started and testing the bot.

### CODE REVIEW

**Comment by ryanvolum** [comment]
Let's make an update to this once we've removed the .bot file, since the .env won't have the properties specified here

**Comment by ryanvolum** [comment]
we should also add a .envsample file that does get checked in, but without any keys

**Comment by KatieProchilo** [comment]
The PR has been updated for removing the bot file, and a .envsample was added.

**Review by ryanvolum — APPROVED** [review]
Made some minor edits - otherwise looks good!

**Pull request merged**
